biliardino/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'biliardino.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('tournament.urls',namespace="tour")),
)

tournament/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from tournament import views, response

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'profile/(?P<player_id>\d+)/$', views.profile, name='profile'),
    url(r'manage/', include('tournament.manage_urls', namespace="manage")),    
    url(r'register/$', response.register, name='register'),
    url(r'login/$', response.user_login, name='login'),
    url(r'logout/$', response.user_logout, name='logout'),
    url(r'facebook/$', response.facebook, name='facebook'),
    url(r'vkontakte/$', response.vkontakte, name='vkontakte'),
    url(r'save_vote/(?P<tour_id>\d+)/$', response.save_vote, name='save_vote'),
    url(r'save_file/$', response.saveFileAvatar, name='save_file'),
    
    url(r'tour/(?P<tour_id>\d+)/$', views.index_tour, name='index_tour'),
    url(r'vote/(?P<tour_id>\d+)/$', views.index_vote, name='vote'),    
    url(r'round/(?P<round_id>\d+)/$', views.index_round, name='index_round'),
    url(r'team/(?P<team_id>\d+)/$', views.index_team, name='index_team'),
    url(r'error/$', views.error_login, name='error_login'),
    )
urlpatterns += patterns('',
        (r'%s(?P<path>.*)' % settings.MEDIA_URL[1:], 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

tournament/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

import sys

reload(sys)
sys.setdefaultencoding('utf-8')

""" DATA BASE MODELS """

class Player(models.Model):
    """
    Playaer - data Base model\n    
    Uses django.auth.user
    """    
    id = models.AutoField(primary_key = True)
    """
    ID - uniq identificator\n
    Primery Key\n
    Auto add, autoincrement\n
    """
    user = models.ForeignKey(User)
    """
    User - link to django auth user\n
    userong for authorization and othe stuff
    """    
    rang = models.IntegerField(default=0)
    """
    Social network ID soon
    """
    fb_id = models.CharField(max_length=200, null=True, blank=True)
    vk_id = models.CharField(max_length=200, null=True, blank=True)
    vk_href = models.CharField(max_length=200, null=True, blank=True)
    avatar = models.CharField(max_length=200, null=True, blank=True)
    def __unicode__(self):  # Python 3: def __str__(self):
        return ('%s %s') % (self.user.first_name,self.user.last_name)
        
    
class Team(models.Model):
    """
    Team - data base model\n
    couple of player
    """
    id = models.AutoField(primary_key = True)
    """ ID """
    players = models.ManyToManyField(Player)
    """ Active, isn't?"""
    active =  models.BooleanField(default = True)
    """ Team name """
    team_name = models.CharField(max_length = 100,blank=True)
    
    avatar = models.CharField(max_length=200, null=True, blank=True)
    
    avatar_file = models.ImageField(upload_to='user_media', null=True, blank=True)
    """
    Goals
    Do not have to store
    """
    goals_me = 0
    goals_my = 0
    points = 0
    games = 0
    win = 0
    loos = 0
    dif = 0
    def __unicode__(self):  # Python 3: def __str__(self):
        return ('%s %s. - %s %s.') % (self.players.all()[0].user.first_name,self.players.all()[0].user.last_name[0], self.players.all()[1].user.first_name,self.players.all()[1].user.last_name[0])

class Tournament(models.Model):
    """
    Tournament - data base model\n
    List of rounds to play
    """
    COMING = 0
    CURRENT = 1
    FINISHED = 2
    STATUS_LIST = (
        (COMING, 'Coming'),
        (CURRENT, 'Current'),
        (FINISHED, 'Finished')
    )
    id = models.AutoField(primary_key = True)
    ""
    title = models.CharField(max_length=100,default="New tournament")
    """Players - ManyToMany field to players"""
    players = models.ManyToManyField(Player, null=True,blank=True)
    """Players, who voted"""
    voted_players = models.ManyToManyField(Player,related_name="voted_players_set",blank=True,null=True)
    """
    Team - ManyToMany
    When teams generated, they'll be added in this field
    """
    teams = models.ManyToManyField(Team, null=True, blank = True)   
    
    end_date = models.DateField(null=True, blank = True)
    
    visible = models.BooleanField(default = True)
    """Status - choice field for status"""
    status = models.SmallIntegerField(choices=STATUS_LIST, default = COMING)
    def __unicode__(self):  # Python 3: def __str__(self):
        return "%s, %s" % (self.title, self.STATUS_LIST[self.status][1])

class Round(models.Model):
    """
    Round - database model
    List of match to play
    """
    REGULAR = 0
    PLAYOFF = 1
    TYPE_LIST = (
        (REGULAR, "Regular"),
        (PLAYOFF, "Play-off")
    )
    id = models.AutoField(primary_key = True)
    """Title of round"""
    title = models.CharField(max_length = 50,default="New round")
    """Tournament realted to"""
    tournament = models.ForeignKey(Tournament)
    """Serial number"""
    serial = models.IntegerField(default = 1)   
    """Round type """
    round_type =  models.SmallIntegerField(choices=TYPE_LIST, default = REGULAR)
    
    active = models.BooleanField(default = False)
    def __unicode__(self):  # Python 3: def __str__(self):
        return "%d %s, %s" % (self.serial,self.title, self.TYPE_LIST[self.round_type][1])

class Match(models.Model):
    """
    Match - database model
    Two teams versus each other
    """    
    CANCELED = 0
    COMING = 1
    FINISHED = 2
    STATUS_LIST = (
        (CANCELED,"Canceled"),
        (COMING,"Coming"),
        (FINISHED,"Finished")
    )
    
    PLAYOFF_LIST = (
                    (0,u"Не выбрано"),
                    (8,"1/8"),
                    (4,"1/4"),
                    (2,"1/2"),
                    (1,u"Финал"),
                    (3,u"Матч на 3-е место"),
    )
    id = models.AutoField(primary_key=True)
    """Round related to """
    round = models.ForeignKey(Round)
    """Title of the match """
    title = models.CharField(max_length = 400, blank=True)
    """Match's play date"""
    play_date = models.DateField(blank=True, null=True)
    
    finish_date = models.DateField(blank=True, null=True)
    """Team A """
    team_a = models.ForeignKey(Team, related_name = "match_team_a")
    """Team B """
    team_b = models.ForeignKey(Team, related_name = "match_team_b")
    """Score of team A"""
    score_a = models.IntegerField(default = 0, null=True, blank=True)
    """Score of team B """
    score_b = models.IntegerField(default = 0, null=True, blank=True)
    """Status of match """
    status =  models.SmallIntegerField(choices=STATUS_LIST, default = COMING)   
    playoff =  models.SmallIntegerField(choices=PLAYOFF_LIST, default = 0)
    def __unicode__(self):  # Python 3: def __str__(self):
        return "M: %s, %s; %s" % (self.team_a,self.team_b,self.playoff)

class Vote(models.Model):
    player = models.ForeignKey(Player)
    tour = models.ForeignKey(Tournament)
    rate = models.IntegerField(default = 0)
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return "%s, %s (%s)" % (self.player,self.rate,self.tour)

tournament/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from tournament.models import Player, Match, Tournament, Round, Team, Vote
from tournament.forms import LoginForm, TourForm, RoundForm, MatchForm, RoundFullForm, TeamForm
from tournament.task import TaskClass
from django.db.models import Q
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
"""
Main page
"""
def index(request):
    tsk = TaskClass()
    login_form = LoginForm() 
    context = {}
    context['login_form'] = login_form
    context['players'] = Player.objects.all()
    
    try:
        tour = Tournament.objects.filter(status=1)[0]        
        current_tour = Tournament.objects.get(id=tour.id).round_set.all().order_by('serial')
        matches = tsk.getMatchesInTour(tour.id)
        players = tour.players.count()
        context['players_count'] = players
        context['matches_count'] = matches
        context['current_tour'] = current_tour
        context['tour'] = tour
    except:
        pass

    try:
        context['tours'] = Tournament.objects.filter(visible=True).all()
        #print context['tours']
    except:
        print("error while index")
    return render(request, 'tournament/user/user_index.html', context)

"""
Public tour page
"""
def index_tour(request, tour_id):     
    login_form = LoginForm() 
    tour = Tournament.objects.get(id=tour_id)
    round_list = Round.objects.filter(tournament=tour).all().order_by('serial')
    voted_percent = (100 / tour.players.count()) * tour.voted_players.count()
    top_list = []
    for plr in tour.players.all():
        try:
            vote = Vote.objects.get(player = plr, tour = tour)
            plr.rang = vote.rate
        except Vote.DoesNotExist:
            plr.rang = 10;
        top_list.append(plr)
    top_list = sorted(top_list, key=lambda x: x.rang, reverse = True)
    
    context = {"tour":tour, "round_list":round_list, 'login_form':login_form, 'voted_percent':voted_percent,'top_list': top_list[:5]}
    return render(request, 'tournament/user/user_tour.html', context)

"""
Public round page
"""
def index_round(request, round_id):
    login_form = LoginForm()
    rnd = Round.objects.get(id=round_id)
    match_list = Match.objects.filter(round=rnd)
    player_list = rnd.tournament.players.all()
    team_list = rnd.tournament.teams.all()
    context = {"match_list":match_list, "round":rnd, 'login_form':login_form, 'player_list':player_list, 'team_list':team_list}
    return render(request, 'tournament/user/user_round.html', context)

"""
Public team page
"""
def index_team(request, team_id):
    tsk = TaskClass()
    team = Team.objects.get(id=team_id)
    print("user id %s") % (request.user.id)
    
    context = {}
    context['team'] = team;
    context['goals'] = tsk.getTeamGoalAtAll(team_id)
    context['match_list'] = Match.objects.filter(Q(team_a=team) | Q(team_b=team)).filter(status=1)
    context['match_list_finished'] = Match.objects.filter(Q(team_a=team) | Q(team_b=team)).filter(status=2)
    try:
        plr = Player.objects.get(user_id=request.user.id)
        my_team = Team.objects.filter(players__in=[plr]).all()
        if team in my_team:
            #print("MY TEAM!!!!")
            context['my_team'] = True
    except:
        pass
    return render(request, 'tournament/user/user_team.html', context)

@login_required(login_url='/')
def index_vote(request, tour_id):    
    #print request.user.id
    player = Player.objects.get(user=request.user)
    tour_vots = Tournament.objects.exclude(id__in=(Tournament.objects.filter(voted_players__in=[player.id]))).filter(status=2, players__in=[player.id])
    tour = Tournament.objects.get(id=tour_id)
    player_list = tour.players.exclude(user = player.user)
    context = {}
    context['list'] = player_list
    if tour in tour_vots:    
        context["tour"] = tour
        return render(request, 'tournament/user/user_vote.html', context)
    else:
        return profile(request, request.user.id)
"""
User's profile
"""
def profile(request, player_id):
    player = Player.objects.get(user_id=player_id)
    teams = Team.objects.filter(players__in=[player.id])
    tours = Tournament.objects.filter(players__in=[player.id]).all()
    matches = Match.objects.filter(Q(team_a__in=teams) | Q(team_b__in=teams)).filter(status=2)
    # Not voted in
    tour_vots = Tournament.objects.exclude(id__in=(Tournament.objects.filter(voted_players__in=[player.id]))).filter(status=2, players__in=[player.id])
    context = {}
    context['tour_vots'] = tour_vots.all()
    context['user_teams'] = teams.all()
    context['player'] = player
    context['tours'] = tours
    context['matches'] = matches
    return render(request, 'tournament/user/profile.html', context)

"""
Manage page
"""
@staff_member_required
def manage(request):    
    if request.method == 'POST':
        form = TourForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/manage/")
    else:
        tours = Tournament.objects.all()
        form = TourForm()
        context = {'tours':tours, 'form': form}
        return render(request, 'tournament/manage/manage.html', context)

"""
Tour's page
"""
@staff_member_required
def tour(request, tour_id=-1):    
    if request.method == 'POST':
        form = RoundFullForm(request.POST)
        if form.is_valid():
            form.save()
            if (tour_id < 0):
                return redirect("/manage/tour/")  # Redirect after POST
            else:
                return redirect("/manage/tour/" + tour_id)  # Redirect after POST
    else:
        context = {}
        form = RoundFullForm()
        if (tour_id > 0):
            tour = Tournament.objects.get(id=tour_id)
            other_players = Player.objects.exclude(id__in=tour.players.all())
            round_list = Round.objects.filter(tournament=tour).all().order_by('serial')
            context = {"round_list":round_list, "form":form, "tour":tour, "other_players":other_players}
        else:
            round_list = Round.objects.all().order_by('serial')
            context = {"round_list":round_list, "form":form}
        return render(request, 'tournament/manage/tour.html', context)


"""
Round's page
"""
@staff_member_required
def round(request, round_id=-1):
    if request.method == "POST":
        form = MatchForm(request.POST)
        if form.is_valid():            
            play_off = request.POST.get('play_off_round')
            if (play_off != "0"):
                print("Save in play-off")
            #print(form.cleaned_data['play_date'])
            form.save()
            if (round_id < 0):
                return redirect("/manage/round/")  # Redirect after POST
            else:
                return redirect("/manage/round/" + round_id)  # Redirect after POST
        else:
            return redirect("/manage/list/match")  # Redirect after POST
    else:
        form = MatchForm()
        context = {}             
        if (round_id > 0):
            rnd = Round.objects.get(id=round_id)
            player_list = rnd.tournament.players.all()
            team_list = rnd.tournament.teams.all()   
            match_list = Match.objects.filter(round=rnd)
            context = {"match_list":match_list, "form":form, "round":rnd, "team_list":team_list, "player_list":player_list}
        else:
            match_list = Match.objects.all()               
            context = {"match_list":match_list, "form":form}
        return render(request, 'tournament/manage/round.html', context)

"""
Match's page
"""
@staff_member_required
def match(request, match_id=-1):
    if (request.method == 'POST'):
        form = TeamForm(request.POST)
        if form.is_valid():
            form.save()
            if match_id == -1:
                return redirect("/manage/list/team")  # Redirect after POST
            else:
                return redirect("/manage/match/%d") % (match_id)  # Redirect after POST
                
    else:
        form = TeamForm()
        if match_id > 0:
            match = Match.objects.get(id=match_id)
            return render(request, 'tournament/manage/match.html', {"match":match, 'form':form})  
        else:        
            return render(request, 'tournament/manage/match.html', {"team_list":Team.objects.all(), 'form':form})  

"""
Team's page
"""
@staff_member_required
def team(request, team_id=-1):
    if team_id > 0:
        team = Team.objects.get(id=team_id)
        return render(request, 'tournament/manage/team.html', {"team":team })
    else:
        return render(request, 'tournament/manage/team.html', {"team_list":Team.objects.all()})

"""
Tournament's page
"""
@staff_member_required
def tournament(request):
    if request.method == 'POST':
        form = TourForm(request.POST)
        if form.is_valid():
            """
            SAVE TOURNAMENT HERE 
            """
            return redirect("/")  # Redirect after POST
    else:
        t_form = TourForm()
        r_form = RoundForm()
        context = {
        'tform':t_form,
        'rform':r_form
        }
    return render(request, 'tournament/manage/tournament.html', context)       

def error_login(request):
    login_form = LoginForm() 
    return render(request, 'tournament/error.html', {"login_form":login_form})

tournament/templates/tournament/user/user_index.html
{% extends "tournament/base.html" %}
{% load staticfiles %}
{% load tournament_extra %}

{% block title %}
Gollasso:: Tournament Manager
{% endblock %}

{% block brand%}

{% endblock %}

{% block user_script %}
<script type="text/javascript">
	var AJAX_FILTER = "{% url 'tour:manage:filter' %}";
	var AJAX_GET_STANDINGS_INDEX = "{% url 'tour:manage:get_match_standings' %}";

</script>

<script src="{% static 'tournament/js/IndexApp.js' %}"></script>
<script src="{% static 'tournament/js/index/IndexController.js' %}"></script>
{% endblock %}
{% block content %}
<div  class="row">
	{% if tour %}
	Текущий турнир:
	<br>
	<span class="fancy-title"><b>{{tour.title}}</b></span>
	<div class="pull-right">
		Участников: {{ players_count }}, Матчей: {{ matches_count }}
	</div>
	<br>
	{% else %}
	<p>
		Турниров пока нет
	</p>
	{% endif %}
	{% for round in current_tour%}
	<div class="teableHeader round-title" round="{{round.id}}" style="border-left: 10px solid #33AD5C;">
		<h3><span>{{round.title}}
			<div class="pull-right">
				<span class="label label-info">{{ round.match_set|set_in_status_length:1 }}</span>
				<span class="label label-success">{{ round.match_set|set_in_status_length:2 }}</span>
				<span class="label">{{ round.match_set|set_in_status_length:0 }}</span>
			</div> </span></h3>
	</div>
	<div class="row " id="round{{round.id}}"  hidden>
		<div class = "span11">
			<a href="{% url 'tour:index_round' round.id %}">Перейти на страницу раунда</a>
		</div>

		<!-- STANDINGS -->
		{% if round.round_type == 0 %}
		<div class="span11">
			<div class="teableHeader" style="margin-top:10px;margin-bottom:5px;">
				Турнирная таблица
			</div>
			<table class="table table-striped resutls-table">
				<thead>
					<tr>
						<th>Место</th>
						<th>Команда</th>
						<th>Участники</th>
						<th></th>
						<th>Игр</th>
						<th>Побед</th>
						<th>Поражений</th>
						<th>Забитые/Пропущеные</th>
						<th>Разница голов</th>
						<th>Очки</th>
					</tr>
				</thead>
				{% for tm in round|round_table%}
				<tr>
					<td>{{ forloop.counter }}</td>
					<td><a href="{% url 'tour:index_team' tm.id %}">
						{% if tm.avatar %}
						<img src="{{tm.avatar}}" width="42" height="42" />
						{%else%}
						<img src="http://badges.infoursquare.com/ipix/423_3.png" width="42" height="42" />
						{%endif%}
						{{ tm.team_name }}
						</a></td>
					<td>
						<a href="{% url 'tour:profile' tm.players.all|player_user_id:0 %}"> 
							{% if tm.players.all|key_ava:0 %} 
							<img src ="{{tm.players.all|key_ava:0}}" width="42"> 
							{% else %} 
							<img src ="{% static 'tournament/img/camera_a.gif' %}" width="42"> 
							{%endif%}

					{{tm.players.all|index:0}} </a> 
					</td><td>
					<a href="{% url 'tour:profile' tm.players.all|player_user_id:1 %}"> 
						{% if tm.players.all|key_ava:1 %} 
						<img src ="{{tm.players.all|key_ava:1}}" width="42"> 
						{% else %} 
						<img src ="{% static 'tournament/img/camera_a.gif' %}" width="42"> 
						{%endif%}

					{{tm.players.all|index:1}} </a></td>
					<td>{{ tm.games}}</td>
					<td>{{ tm.win}}</td>
					<td>{{ tm.loos}}</td>
					<td>{{ tm.goals_my}} / {{ tm.goals_me}}</td>
					<td>{{ tm.dif}}</td>
					<td>{{ tm.points}}</td>
				</tr>
				{% endfor %}
			</table>
		</div>
		{% else%}

			<p>Таблица Play-off на странице раунда</p>

		{% endif %}
		<div class="span11 teableHeader">
			Матчи раунда
		</div>
		<div class="span5">
			<table class="table table-condensed">
				<span class="label label-info" style="width: 100%;">Предстоящие: {{ round.match_set|set_in_status_length:1 }}</span>
				<thead>
					<tr>

						<th>Название</th>
						<th>Комманда А</th>
						<th>Комманда Б</th>

					</tr>
				</thead>
				{% for match in round.match_set|in_status:1%}
				<tr>
					<td>{{match.title}}</td>
					<td><a href="{% url 'tour:index_team' match.team_a.id %}">{{match.team_a.team_name}}</a></td>
					<td><a href="{% url 'tour:index_team' match.team_b.id %}">{{match.team_b.team_name}}</a></td>
				</tr>
				{% empty %}
				Матчей нет
				{% endfor %}
			</table>
		</div>

		<div class="span6">
			<table class="table table-condensed">
				<span class="label label-success" style="width: 100%;">Завершенные:  {{ round.match_set|set_in_status_length:2 }}</span>
				<thead>
					<tr>
						<th>Название</th>
						<th>Комманда А</th>
						<th>Комманда Б</th>
						<th>Счет</td>
					</tr>
				</thead>
				{% for match in round.match_set|in_status:2%}
				<tr>
					<td>{{match.title}}</td>
					<td><a href="{% url 'tour:index_team' match.team_a.id %}">{{match.team_a.team_name}}</a></td>
					<td><a href="{% url 'tour:index_team' match.team_b.id %}">{{match.team_b.team_name}}</a></td>
					<td>{{ match.score_a}} : {{ match.score_b}} </td>
				</tr>
				{% empty %}
				<tr>
					<td> Матчей нет </td>
				</tr>
				{% endfor %}
			</table>
		</div>
	</div>

	{% endfor %}

</div>
<div class="row">
	<hr>
	<div style="margin:10px;"></div>
	<div class="span5 manage-table" id="tourTable">
		<div class="teableHeader">
			Турниры
			<select class="pull-right" id="tour_filter">
				<option selected="selected" value="-1">Все</option>
				<option value="0">Предстоящие</option>
				<option value="1">Текущие</option>
				<option value="2">Завершенные</option>
			</select>
		</div>
		<table class="table round-table" >
			<thead>
				<tr>
					<th>#</th>
					<th>Title</th>
					<th>Status</th>
					<th>Players</th>
					<th>Teams</th>
				</tr>
			</thead>
			<tbody id = "tour_table">
				{% for tour in tours %}
				<tr>
					<td> {{ tour.id }} </td>
					<td><a href="{% url 'tour:index_tour' tour.id %}">{{tour.title}}</a></td>
					<td>{{tour.STATUS_LIST|key:tour.status}}</td>
					<td>{{ tour.players.count }}</td>
					<td>{{ tour.teams.count }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<div class="tableFooter"></div>
	</div>

	<div class="span5 manage-table" id="tourTable">
		<div class="teableHeader">
			Игроки
			<div class="pull-right">
				<input type="text" class="input-medium search-query" id="userName">
				<button type="submit" class="btn" id="doSearchUser">
					Найти
				</button>
			</div>
		</div>
		<table class="table round-table" id = "tour_table">
			Всего: {{players.count}}
			<tbody id = "userList">
				{% for plr in players %}
				<tr>
					<td><a href="{% url 'tour:profile' plr.user.id %}">{{ plr }} </a></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<div class="tableFooter"></div>
	</div>
</div>
{% endblock %}

tournament/templates/tournament/user/user_vote.html
{% extends "tournament/base.html" %}
{% load staticfiles %}
{% load tournament_extra %}
{% block title %}
	Gollasso:: Tournament Manager
{% endblock %}

{% block user_script %}
<link href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" rel="stylesheet">
<script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script src="{% static 'tournament/js/IndexApp.js' %}"></script>
<script src="{% static 'tournament/js/index/IndexController.js' %}"></script>
<script>
var AJAX_SAVE_VOTE = "{% url 'tour:save_vote' tour.id %}";
var USER_ID = "{{ user.id }}";
$(document).ready(function(){
	$( "#sortable" ).sortable();
    $( "#sortable" ).disableSelection();
});
	
</script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="teableHeader">
			Расположите игроков в соответсвие с их навыком игры, лучший вверху. Проголосовать можно только один раз.
		</div>
	<div class="span6">
		<div>
			<br>
		</div>		
		
		<ul id="sortable">
		{% for player in list %}
		 <li class='ui-state-default' player_id = "{{player.id}}">
		 	{% if player.avatar %}
		 	<img src="{{player.avatar}}" width="30" align="left" style="margin-right:5px;" />
		 	{% endif %}
		 	<a href = "{% url 'tour:profile' player.user.id %}" target="_blank">{{player}}</a>
		 </li>
		{% endfor%}
		</ul>
		<div class="pull-right">
		<button class="btn btn-success" id = "sendVote">
			<div id="loading" hidden>
				&nbsp;&nbsp;&nbsp;&nbsp; <img id="loading" class="loadingImage" src = "{% static 'tournament/img/loading.GIF' %}"> &nbsp;&nbsp;&nbsp;&nbsp;
			</div>
			<div id="notLoading" >
			&nbsp;&nbsp;&nbsp;&nbsp; Готово &nbsp;&nbsp;&nbsp;&nbsp;
			</div>
			</button>
		</div>		
	</div>
</div>	
{% endblock %}